#!/bin/bash
# Install the full TeX Live distribution into $PREFIX.
# Uses the upstream install-tl script from CTAN with --scheme-full.
# Disk usage: ~7 GB. No sudo, no interactive input.
#
# Layout (under $PREFIX):
#   $PREFIX/texlive/<year>/             — TEXDIR (binaries, packages)
#   $PREFIX/texlive/texmf-local/        — TEXMFLOCAL (site-wide additions)
#
# Symlinks for pdflatex/xelatex/tlmgr/... are placed in $PREFIX/bin via
# `tlmgr path add` once the install completes.

set -euo pipefail

PREFIX="${PREFIX:-$HOME/local}"
BIN="$PREFIX/bin"
SRC="$PREFIX/src"
TEXLIVE_ROOT="${TEXLIVE_ROOT:-$PREFIX/texlive}"
mkdir -p "$BIN" "$SRC" "$TEXLIVE_ROOT"
export PATH="$BIN:$PATH"

if [ -x "$BIN/pdflatex" ] && [ -x "$BIN/tlmgr" ]; then
  echo "  TeX Live already linked into $BIN, skipping."
  echo "    $("$BIN/pdflatex" --version | head -1)"
  exit 0
fi

# Pick a year-specific TEXDIR by reading the installer once it's downloaded.
# We use the CTAN "current year" mirror; install-tl picks the right tree.
INSTALLER_DIR="$SRC/install-tl"
INSTALLER_URL="https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"

echo "==> Downloading TeX Live installer"
rm -rf "$INSTALLER_DIR"
mkdir -p "$INSTALLER_DIR"
cd "$INSTALLER_DIR"
curl -fL --retry 3 --retry-delay 2 -o install-tl-unx.tar.gz "$INSTALLER_URL"
tar xf install-tl-unx.tar.gz --strip-components=1
rm -f install-tl-unx.tar.gz

PROFILE="$INSTALLER_DIR/texlive.profile"
cat > "$PROFILE" <<EOF
# TeX Live installer profile — generated by install_texlive.sh
selected_scheme scheme-full
TEXDIR $TEXLIVE_ROOT/current
TEXMFLOCAL $TEXLIVE_ROOT/texmf-local
TEXMFSYSCONFIG $TEXLIVE_ROOT/current/texmf-config
TEXMFSYSVAR $TEXLIVE_ROOT/current/texmf-var
TEXMFCONFIG ~/.texlive/texmf-config
TEXMFHOME ~/texmf
TEXMFVAR ~/.texlive/texmf-var
binary_x86_64-linux 1
instopt_adjustpath 0
instopt_adjustrepo 1
instopt_letter 0
instopt_portable 0
instopt_write18_restricted 1
tlpdbopt_autobackup 1
tlpdbopt_backupdir tlpkg/backups
tlpdbopt_create_formats 1
tlpdbopt_desktop_integration 0
tlpdbopt_file_assocs 0
tlpdbopt_generate_updmap 0
tlpdbopt_install_docfiles 1
tlpdbopt_install_srcfiles 1
tlpdbopt_post_code 1
tlpdbopt_sys_bin $BIN
tlpdbopt_sys_info $TEXLIVE_ROOT/current/share/info
tlpdbopt_sys_man $TEXLIVE_ROOT/current/share/man
tlpdbopt_w32_multi_user 1
EOF

echo "==> Running install-tl (this downloads ~5 GB and takes a while)"
./install-tl --profile "$PROFILE" --no-interaction

# Locate the bin dir TeX Live just installed and add it to $PREFIX/bin.
TL_BIN="$(find "$TEXLIVE_ROOT/current/bin" -mindepth 1 -maxdepth 1 -type d | head -1)"
if [ -z "${TL_BIN:-}" ] || [ ! -x "$TL_BIN/tlmgr" ]; then
  echo "ERROR: could not locate tlmgr under $TEXLIVE_ROOT/current/bin" >&2
  exit 1
fi

echo "==> Linking TeX Live commands → $BIN"
"$TL_BIN/tlmgr" option sys_bin "$BIN" >/dev/null
"$TL_BIN/tlmgr" path add >/dev/null

echo "    $("$BIN/pdflatex" --version | head -1)"
echo
echo "    Update packages with:  tlmgr update --self --all"
