vim.filetype.add({
  extension = {
    bash = "bash",
    c = "c",
    cc = "cpp",
    cmake = "cmake",
    cpp = "cpp",
    cu = "cuda",
    cuh = "cuda",
    cxx = "cpp",
    h = "c",
    hh = "cpp",
    hpp = "cpp",
    hxx = "cpp",
    inl = "cpp",
    ipp = "cpp",
    py = "python",
    sh = "sh",
    tpp = "cpp",
    yaml = "yaml",
    yml = "yaml",
    zsh = "zsh",
  },
  filename = {
    ["CMakeLists.txt"] = "cmake",
    [".bashrc"] = "bash",
    [".profile"] = "sh",
    [".zprofile"] = "zsh",
    [".zshrc"] = "zsh",
  },
  pattern = {
    ["bashrc%..*"] = "bash",
    ["zshrc%..*"] = "zsh",
  },
})
